login: &login
  adapter: mysql
  username: demo
  password: demo
  host: localhost
  encoding: utf8
#  socket: /var/lib/mysql/mysql.sock

development:
  <<: *login
  database: demowatch

test:
  <<: *login
  database: demo_test

production:
  <<: *login
  database: demo_dev

